name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake

    - name: Clean previous build
      run: rm -rf build

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: cmake ..

    - name: Build
      working-directory: ./build
      run: make

    - name: Run tests
      working-directory: ./build
      run: ./CompositePatternTestTest

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./build/CompositePatternTestTest